title       = "doh"
baseURL     = "https://doh-cli.tamnd.com/"
description = "A command line for doh."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/doh-cli"
